import type { NextPage } from "next";
import Head from "next/head";
import { SearchDocumentApp } from "../../src/components/organisms/SearchDocumentApp";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>IR Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to IR Site !</h1>

        <div style={{ margin: "100px 0" }}>
          <SearchDocumentApp />
        </div>
      </main>
    </div>
  );
};

export default Home;
